apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mssql
    env: staging
  name: mssql
  namespace: staging-mssql
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mssql
      env: staging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
        env: staging
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2017-latest
        imagePullPolicy: Always
        name: mssql
        resources:
          requests:
            cpu: 1000m
            memory: 4G
        volumeMounts:
        - mountPath: /var/opt/mssql # <--- mount point for dba files
          name: pvc-mssql-staging
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pvc-mssql-staging
        persistentVolumeClaim:
          claimName: pvc-mssql-staging
