apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mssql
    env: staging
    type: nfs
  name: pvc-mssql-staging
  namespace: staging-mssql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-mssql-staging
